# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/dotnet/sdk:5.0-focal 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests*.csproj'
